# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akirachix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(default='Good student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='names',
            field=models.TextField(max_length=100),
        ),
    ]
